import type { CropProfile } from "@/types/crops";

export const CROPS: CropProfile[] = [
  // ── CEREALS ──────────────────────────────────────────────────────────
  {
    id: "maize",
    name: "Maize",
    emoji: "🌽",
    category: "cereal",
    idealTemperature: [18, 32],
    rainfallNeeds: "moderate",
    humidityRange: [50, 80],
    growingSeasons: ["March–July", "October–January"],
    sensitivity: ["frost", "flooding", "drought at tasseling"],
    description: "Warm-season cereal requiring consistent moisture during tasseling and grain fill.",
  },
  {
    id: "wheat",
    name: "Wheat",
    emoji: "🌾",
    category: "cereal",
    idealTemperature: [12, 24],
    rainfallNeeds: "moderate",
    humidityRange: [40, 70],
    growingSeasons: ["October–March"],
    sensitivity: ["excess moisture", "rust disease", "heat at flowering"],
    description: "Cool-season grain sensitive to high humidity and waterlogging.",
  },
  {
    id: "rice",
    name: "Rice",
    emoji: "🍚",
    category: "cereal",
    idealTemperature: [20, 35],
    rainfallNeeds: "high",
    humidityRange: [70, 90],
    growingSeasons: ["March–July", "August–December"],
    sensitivity: ["drought", "cold at flowering", "blast disease"],
    description: "Paddy crop requiring standing water or very high soil moisture.",
  },
  {
    id: "sorghum",
    name: "Sorghum",
    emoji: "🌿",
    category: "cereal",
    idealTemperature: [20, 38],
    rainfallNeeds: "low",
    humidityRange: [30, 65],
    growingSeasons: ["February–June", "September–December"],
    sensitivity: ["waterlogging", "bird damage at grain fill"],
    description: "Drought-tolerant cereal well-suited to semi-arid regions.",
  },
  {
    id: "millet",
    name: "Millet",
    emoji: "🌾",
    category: "cereal",
    idealTemperature: [22, 38],
    rainfallNeeds: "low",
    humidityRange: [25, 60],
    growingSeasons: ["April–August"],
    sensitivity: ["waterlogging", "downy mildew", "smut"],
    description: "Highly drought-tolerant staple for arid and semi-arid zones.",
  },
  {
    id: "barley",
    name: "Barley",
    emoji: "🌾",
    category: "cereal",
    idealTemperature: [10, 22],
    rainfallNeeds: "moderate",
    humidityRange: [40, 70],
    growingSeasons: ["October–February"],
    sensitivity: ["leaf rust", "net blotch", "heat stress"],
    description: "Cool-season cereal used for food, feed, and brewing.",
  },

  // ── LEGUMES ──────────────────────────────────────────────────────────
  {
    id: "beans",
    name: "Common Beans",
    emoji: "🫘",
    category: "legume",
    idealTemperature: [16, 26],
    rainfallNeeds: "moderate",
    humidityRange: [50, 75],
    growingSeasons: ["March–August", "October–January"],
    sensitivity: ["flooding", "drought at flowering", "rust", "angular leaf spot"],
    description: "Protein-rich legume requiring good drainage and moderate moisture.",
  },
  {
    id: "soybeans",
    name: "Soybeans",
    emoji: "🫘",
    category: "legume",
    idealTemperature: [20, 30],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["March–July"],
    sensitivity: ["frost", "waterlogging", "pod shattering in dry heat"],
    description: "High-protein oilseed legume with strong nitrogen-fixation.",
  },
  {
    id: "groundnuts",
    name: "Groundnuts",
    emoji: "🥜",
    category: "legume",
    idealTemperature: [20, 33],
    rainfallNeeds: "moderate",
    humidityRange: [50, 75],
    growingSeasons: ["March–July", "October–January"],
    sensitivity: ["waterlogging", "aflatoxin in drought stress", "rosette virus"],
    description: "Legume that pegs pods underground; needs well-drained sandy loam.",
  },
  {
    id: "cowpeas",
    name: "Cowpeas",
    emoji: "🫘",
    category: "legume",
    idealTemperature: [20, 35],
    rainfallNeeds: "low",
    humidityRange: [40, 70],
    growingSeasons: ["February–May", "September–November"],
    sensitivity: ["waterlogging", "aphids", "pod borer"],
    description: "Heat and drought-tolerant legume for marginal soils.",
  },
  {
    id: "pigeon_peas",
    name: "Pigeon Peas",
    emoji: "🫛",
    category: "legume",
    idealTemperature: [18, 30],
    rainfallNeeds: "low",
    humidityRange: [40, 70],
    growingSeasons: ["March–October"],
    sensitivity: ["waterlogging", "Fusarium wilt", "pod fly"],
    description: "Perennial/annual shrub legume tolerant of poor soils.",
  },
  {
    id: "lentils",
    name: "Lentils",
    emoji: "🫘",
    category: "legume",
    idealTemperature: [12, 24],
    rainfallNeeds: "low",
    humidityRange: [30, 65],
    growingSeasons: ["October–March"],
    sensitivity: ["excess moisture", "botrytis grey mould", "heat at flowering"],
    description: "Cool-season pulse with low water requirements.",
  },

  // ── VEGETABLES ───────────────────────────────────────────────────────
  {
    id: "tomatoes",
    name: "Tomatoes",
    emoji: "🍅",
    category: "vegetable",
    idealTemperature: [20, 30],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Year-round with irrigation"],
    sensitivity: ["late blight", "excess humidity", "frost", "blossom drop above 35°C"],
    description: "Warm-season vegetable highly susceptible to fungal disease in wet conditions.",
  },
  {
    id: "potatoes",
    name: "Potatoes",
    emoji: "🥔",
    category: "vegetable",
    idealTemperature: [15, 22],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["March–June", "September–December"],
    sensitivity: ["late blight", "frost", "waterlogging", "heat above 30°C"],
    description: "Cool-season tuber prone to late blight in humid conditions.",
  },
  {
    id: "onions",
    name: "Onions",
    emoji: "🧅",
    category: "vegetable",
    idealTemperature: [13, 24],
    rainfallNeeds: "moderate",
    humidityRange: [50, 70],
    growingSeasons: ["October–February", "June–September"],
    sensitivity: ["purple blotch", "downy mildew", "excess moisture at bulbing"],
    description: "Bulb crop sensitive to high humidity near maturity.",
  },
  {
    id: "cabbage",
    name: "Cabbage",
    emoji: "🥬",
    category: "vegetable",
    idealTemperature: [12, 22],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Year-round in highlands"],
    sensitivity: ["black rot", "club root", "excess heat"],
    description: "Cool-season brassica thriving in highland climates.",
  },
  {
    id: "kale",
    name: "Kale / Sukuma Wiki",
    emoji: "🥦",
    category: "vegetable",
    idealTemperature: [10, 25],
    rainfallNeeds: "moderate",
    humidityRange: [55, 80],
    growingSeasons: ["Year-round"],
    sensitivity: ["aphids", "diamondback moth", "black rot"],
    description: "Hardy brassica; very popular kitchen garden crop across East Africa.",
  },
  {
    id: "spinach",
    name: "Spinach",
    emoji: "🥬",
    category: "vegetable",
    idealTemperature: [10, 22],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Year-round in cool areas"],
    sensitivity: ["downy mildew", "bolting in heat", "leaf miners"],
    description: "Fast-growing leafy green for cool or irrigated conditions.",
  },
  {
    id: "carrots",
    name: "Carrots",
    emoji: "🥕",
    category: "vegetable",
    idealTemperature: [15, 22],
    rainfallNeeds: "moderate",
    humidityRange: [55, 75],
    growingSeasons: ["Year-round in highlands"],
    sensitivity: ["carrot fly", "forking in stony soils", "Alternaria blight"],
    description: "Root vegetable requiring deep, well-drained, stone-free soil.",
  },
  {
    id: "peppers",
    name: "Peppers / Capsicum",
    emoji: "🌶️",
    category: "vegetable",
    idealTemperature: [20, 30],
    rainfallNeeds: "moderate",
    humidityRange: [55, 75],
    growingSeasons: ["Year-round with irrigation"],
    sensitivity: ["Phytophthora blight", "blossom drop above 35°C", "frost"],
    description: "Warm-season vegetable; needs consistent moisture and warm nights.",
  },
  {
    id: "eggplant",
    name: "Eggplant / Brinjal",
    emoji: "🍆",
    category: "vegetable",
    idealTemperature: [22, 32],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Year-round with irrigation"],
    sensitivity: ["bacterial wilt", "spider mites in dry conditions", "frost"],
    description: "Tropical vegetable well-suited to warm lowland conditions.",
  },
  {
    id: "cucumber",
    name: "Cucumber",
    emoji: "🥒",
    category: "vegetable",
    idealTemperature: [22, 32],
    rainfallNeeds: "moderate",
    humidityRange: [70, 90],
    growingSeasons: ["Year-round with irrigation"],
    sensitivity: ["powdery mildew", "downy mildew", "frost", "waterlogging"],
    description: "Fast-growing cucurbit needing warm temperatures and consistent irrigation.",
  },
  {
    id: "pumpkin",
    name: "Pumpkin / Squash",
    emoji: "🎃",
    category: "vegetable",
    idealTemperature: [18, 30],
    rainfallNeeds: "moderate",
    humidityRange: [50, 75],
    growingSeasons: ["March–July", "October–December"],
    sensitivity: ["powdery mildew", "fruit fly", "frost"],
    description: "Trailing vine crop with good drought tolerance once established.",
  },

  // ── CASH CROPS ───────────────────────────────────────────────────────
  {
    id: "tea",
    name: "Tea",
    emoji: "🍃",
    category: "cash_crop",
    idealTemperature: [14, 25],
    rainfallNeeds: "high",
    humidityRange: [70, 90],
    growingSeasons: ["Year-round"],
    sensitivity: ["drought", "frost", "waterlogging", "blister blight"],
    description: "Perennial highland crop requiring high, well-distributed rainfall.",
  },
  {
    id: "coffee",
    name: "Coffee",
    emoji: "☕",
    category: "cash_crop",
    idealTemperature: [15, 24],
    rainfallNeeds: "high",
    humidityRange: [60, 80],
    growingSeasons: ["October–December (harvest)"],
    sensitivity: ["frost", "extreme heat", "coffee berry disease", "leaf rust"],
    description: "Highland crop needing distinct dry periods for flowering trigger.",
  },
  {
    id: "sugarcane",
    name: "Sugarcane",
    emoji: "🎋",
    category: "cash_crop",
    idealTemperature: [20, 35],
    rainfallNeeds: "high",
    humidityRange: [65, 85],
    growingSeasons: ["Year-round (18-month cycle)"],
    sensitivity: ["frost", "waterlogging", "smut disease", "drought at grand growth"],
    description: "Tall grass requiring high rainfall or irrigation; 12–18 month cycle.",
  },
  {
    id: "cotton",
    name: "Cotton",
    emoji: "🌸",
    category: "cash_crop",
    idealTemperature: [20, 35],
    rainfallNeeds: "moderate",
    humidityRange: [40, 65],
    growingSeasons: ["February–October"],
    sensitivity: ["bollworm", "excess moisture at boll opening", "frost"],
    description: "Warm-season fibre crop needing dry conditions during boll opening.",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    emoji: "🌻",
    category: "cash_crop",
    idealTemperature: [20, 35],
    rainfallNeeds: "low",
    humidityRange: [40, 65],
    growingSeasons: ["February–June"],
    sensitivity: ["waterlogging", "downy mildew", "sclerotinia"],
    description: "Drought-tolerant oilseed crop well-suited to semi-arid regions.",
  },
  {
    id: "tobacco",
    name: "Tobacco",
    emoji: "🍂",
    category: "cash_crop",
    idealTemperature: [18, 28],
    rainfallNeeds: "moderate",
    humidityRange: [55, 75],
    growingSeasons: ["November–April"],
    sensitivity: ["blue mould", "black shank", "excess nitrogen"],
    description: "Cash crop requiring well-drained sandy loam and careful curing conditions.",
  },

  // ── FRUITS ───────────────────────────────────────────────────────────
  {
    id: "banana",
    name: "Banana",
    emoji: "🍌",
    category: "fruit",
    idealTemperature: [18, 30],
    rainfallNeeds: "high",
    humidityRange: [75, 90],
    growingSeasons: ["Year-round"],
    sensitivity: ["Panama disease", "black Sigatoka", "strong winds", "drought"],
    description: "Perennial tropical fruit requiring consistent warmth and high moisture.",
  },
  {
    id: "mango",
    name: "Mango",
    emoji: "🥭",
    category: "fruit",
    idealTemperature: [22, 35],
    rainfallNeeds: "low",
    humidityRange: [40, 70],
    growingSeasons: ["Harvests: October–December, March–June"],
    sensitivity: ["anthracnose in wet conditions", "mango weevil", "excess rain at flowering"],
    description: "Tropical tree fruit needing a dry period to trigger flowering.",
  },
  {
    id: "avocado",
    name: "Avocado",
    emoji: "🥑",
    category: "fruit",
    idealTemperature: [16, 28],
    rainfallNeeds: "moderate",
    humidityRange: [55, 80],
    growingSeasons: ["Harvests: May–September"],
    sensitivity: ["Phytophthora root rot", "frost", "excess wind", "waterlogging"],
    description: "Subtropical tree fruit highly sensitive to waterlogged soils.",
  },
  {
    id: "pineapple",
    name: "Pineapple",
    emoji: "🍍",
    category: "fruit",
    idealTemperature: [20, 30],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Year-round (18-month cycle)"],
    sensitivity: ["mealybug wilt", "heart rot", "frost"],
    description: "Bromeliad tolerant of drought; sensitive to cold and waterlogging.",
  },
  {
    id: "papaya",
    name: "Papaya",
    emoji: "🍈",
    category: "fruit",
    idealTemperature: [22, 32],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Year-round"],
    sensitivity: ["PRSV virus", "frost", "waterlogging", "strong winds"],
    description: "Fast-fruiting tropical tree; very frost-sensitive.",
  },
  {
    id: "passion_fruit",
    name: "Passion Fruit",
    emoji: "🍋",
    category: "fruit",
    idealTemperature: [18, 26],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Year-round in highlands"],
    sensitivity: ["woodiness virus", "Fusarium wilt", "excess humidity"],
    description: "Vine fruit thriving in East African highland conditions.",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    emoji: "🍓",
    category: "fruit",
    idealTemperature: [12, 22],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Year-round in cool highlands"],
    sensitivity: ["botrytis grey mould", "verticillium wilt", "excess heat"],
    description: "Cool-season fruit crop suited to highland conditions.",
  },

  // ── TUBERS & ROOTS ───────────────────────────────────────────────────
  {
    id: "cassava",
    name: "Cassava",
    emoji: "🥔",
    category: "tuber",
    idealTemperature: [20, 34],
    rainfallNeeds: "low",
    humidityRange: [40, 75],
    growingSeasons: ["Year-round"],
    sensitivity: ["cassava mosaic disease", "cassava brown streak", "waterlogging"],
    description: "Drought-tolerant starchy staple; major food security crop.",
  },
  {
    id: "sweet_potato",
    name: "Sweet Potato",
    emoji: "🍠",
    category: "tuber",
    idealTemperature: [20, 30],
    rainfallNeeds: "moderate",
    humidityRange: [55, 80],
    growingSeasons: ["Year-round"],
    sensitivity: ["weevil damage", "waterlogging", "viral diseases"],
    description: "Nutritious tuber with good drought tolerance once established.",
  },
  {
    id: "arrowroot",
    name: "Arrowroot",
    emoji: "🌿",
    category: "tuber",
    idealTemperature: [18, 28],
    rainfallNeeds: "high",
    humidityRange: [70, 90],
    growingSeasons: ["Year-round near water"],
    sensitivity: ["drought", "low temperatures"],
    description: "Aquatic-margin tuber thriving in wet, waterlogged conditions.",
  },

  // ── HERBS & SPICES ───────────────────────────────────────────────────
  {
    id: "ginger",
    name: "Ginger",
    emoji: "🫚",
    category: "spice",
    idealTemperature: [20, 30],
    rainfallNeeds: "high",
    humidityRange: [70, 90],
    growingSeasons: ["March–November"],
    sensitivity: ["bacterial wilt", "root rot in waterlogged soils", "drought"],
    description: "Rhizome spice requiring humid, warm conditions with good drainage.",
  },
  {
    id: "garlic",
    name: "Garlic",
    emoji: "🧄",
    category: "spice",
    idealTemperature: [12, 22],
    rainfallNeeds: "low",
    humidityRange: [40, 65],
    growingSeasons: ["September–February"],
    sensitivity: ["purple blotch", "white rot", "excess moisture at bulbing"],
    description: "Cool-season bulb crop needing dry conditions at harvest.",
  },
  {
    id: "coriander",
    name: "Coriander",
    emoji: "🌿",
    category: "spice",
    idealTemperature: [15, 25],
    rainfallNeeds: "low",
    humidityRange: [40, 65],
    growingSeasons: ["Year-round in cool areas"],
    sensitivity: ["bolting in heat", "Alternaria leaf blight", "aphids"],
    description: "Fast-growing herb that bolts quickly in hot weather.",
  },

  // ── AGROFORESTRY ─────────────────────────────────────────────────────
  {
    id: "macadamia",
    name: "Macadamia",
    emoji: "🌰",
    category: "tree_crop",
    idealTemperature: [15, 25],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Harvest: March–August"],
    sensitivity: ["husk spot", "stink bug", "frost during flowering"],
    description: "Highland tree nut requiring well-distributed rainfall.",
  },
  {
    id: "eucalyptus",
    name: "Eucalyptus",
    emoji: "🌳",
    category: "tree_crop",
    idealTemperature: [15, 30],
    rainfallNeeds: "low",
    humidityRange: [30, 65],
    growingSeasons: ["Year-round"],
    sensitivity: ["frost when young", "termites"],
    description: "Fast-growing timber and fuelwood tree tolerant of poor soils.",
  },
  {
    id: "grevillea",
    name: "Grevillea",
    emoji: "🌲",
    category: "tree_crop",
    idealTemperature: [14, 28],
    rainfallNeeds: "low",
    humidityRange: [40, 75],
    growingSeasons: ["Year-round"],
    sensitivity: ["waterlogging", "frost when young"],
    description: "Popular agroforestry shade tree used with tea and coffee.",
  },
];

export const CROP_CATEGORIES = [
  { id: "all", label: "All Crops" },
  { id: "cereal", label: "Cereals" },
  { id: "legume", label: "Legumes" },
  { id: "vegetable", label: "Vegetables" },
  { id: "cash_crop", label: "Cash Crops" },
  { id: "fruit", label: "Fruits" },
  { id: "tuber", label: "Tubers" },
  { id: "spice", label: "Spices" },
  { id: "tree_crop", label: "Tree Crops" },
] as const;

export function getCropById(id: string): CropProfile | undefined {
  return CROPS.find(c => c.id === id);
}

export function getCropsByCategory(category: string): CropProfile[] {
  if (category === "all") return CROPS;
  return CROPS.filter(c => c.category === category);
}
