import type { CropProfile } from "@/types/crops";

export const CROPS: CropProfile[] = [
  {
    id: "maize",
    name: "Maize",
    emoji: "🌽",
    idealTemperature: [18, 30],
    rainfallNeeds: "moderate",
    humidityRange: [50, 80],
    growingSeasons: ["March-July", "October-January"],
    sensitivity: ["frost", "flooding", "drought"],
    description: "Warm-season cereal requiring consistent moisture during tasseling.",
  },
  {
    id: "wheat",
    name: "Wheat",
    emoji: "🌾",
    idealTemperature: [12, 24],
    rainfallNeeds: "moderate",
    humidityRange: [40, 70],
    growingSeasons: ["October-March"],
    sensitivity: ["excess moisture", "rust disease", "heat"],
    description: "Cool-season grain sensitive to high humidity and waterlogging.",
  },
  {
    id: "tea",
    name: "Tea",
    emoji: "🍃",
    idealTemperature: [14, 25],
    rainfallNeeds: "high",
    humidityRange: [70, 90],
    growingSeasons: ["Year-round"],
    sensitivity: ["drought", "frost", "waterlogging"],
    description: "Perennial crop requiring high, well-distributed rainfall.",
  },
  {
    id: "coffee",
    name: "Coffee",
    emoji: "☕",
    idealTemperature: [15, 24],
    rainfallNeeds: "high",
    humidityRange: [60, 80],
    growingSeasons: ["October-December (harvest)"],
    sensitivity: ["frost", "extreme heat", "coffee berry disease"],
    description: "Highland crop needing distinct dry periods for flowering.",
  },
  {
    id: "tomatoes",
    name: "Tomatoes",
    emoji: "🍅",
    idealTemperature: [20, 30],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["Year-round with irrigation"],
    sensitivity: ["blight", "excess humidity", "frost"],
    description: "Warm-season vegetable highly susceptible to fungal disease in wet conditions.",
  },
  {
    id: "potatoes",
    name: "Potatoes",
    emoji: "🥔",
    idealTemperature: [15, 22],
    rainfallNeeds: "moderate",
    humidityRange: [60, 80],
    growingSeasons: ["March-June", "September-December"],
    sensitivity: ["late blight", "frost", "waterlogging"],
    description: "Cool-season tuber crop prone to late blight in humid conditions.",
  },
  {
    id: "beans",
    name: "Beans",
    emoji: "🫘",
    idealTemperature: [16, 26],
    rainfallNeeds: "moderate",
    humidityRange: [50, 75],
    growingSeasons: ["March-August", "October-January"],
    sensitivity: ["flooding", "drought during flowering", "rust"],
    description: "Legume requiring good drainage and moderate moisture.",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    emoji: "🌻",
    idealTemperature: [20, 35],
    rainfallNeeds: "low",
    humidityRange: [40, 65],
    growingSeasons: ["February-June"],
    sensitivity: ["waterlogging", "downy mildew"],
    description: "Drought-tolerant oilseed crop well-suited to semi-arid regions.",
  },
];

export function getCropById(id: string): CropProfile | undefined {
  return CROPS.find((c) => c.id === id);
}
